//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCDGear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string MoreIMG { get; set; }
        public Nullable<int> Type { get; set; }
        public bool Status { get; set; }
    }
}
