//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCDGear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string MoreImages { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public int Quantity { get; set; }
        public string LinkVideo { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public string Detail { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescriptions { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string CPU { get; set; }
        public string OperatingSystem { get; set; }
        public string RAM { get; set; }
        public string GPU { get; set; }
        public string Screen { get; set; }
        public string SSDHardDrive { get; set; }
        public string ConnectionPorts { get; set; }
        public string Keyboard { get; set; }
        public string Pin { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
